//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/IA_Main.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/IA_Main.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @IA_Main: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @IA_Main()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""IA_Main"",
    ""maps"": [
        {
            ""name"": ""AM_Player"",
            ""id"": ""c13407c4-478d-4367-aa0e-cfffa8be7e41"",
            ""actions"": [
                {
                    ""name"": ""A_Move"",
                    ""type"": ""Value"",
                    ""id"": ""c8a47dd0-ad66-403d-8fb1-c267089e9405"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A_Look"",
                    ""type"": ""Value"",
                    ""id"": ""3f48bd84-8b92-41d4-b042-5de7bb53d7f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A_Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""5d4b8180-9cba-4c72-9f2c-1e1889e0d679"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A_Jump"",
                    ""type"": ""Button"",
                    ""id"": ""29d8339e-1691-4d35-af36-460b443b47b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a634c1e7-2b81-4c65-ab61-68fede5a3605"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""A_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7915d08b-8639-4248-9a71-77673e5129d6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dc2665c1-36fc-4764-afba-72a1be1c4724"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a538105a-49d4-4226-8d24-061fcd30913b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""46d8e8a9-232a-4d8b-b042-740aa0d07197"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ea9f0a1f-917e-4e67-8969-9621172b3c3d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3501da07-c9cc-4163-b12f-0f6e7ec29e34"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3421f190-0404-4973-86a4-052d1fe8959b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AM_Player
        m_AM_Player = asset.FindActionMap("AM_Player", throwIfNotFound: true);
        m_AM_Player_A_Move = m_AM_Player.FindAction("A_Move", throwIfNotFound: true);
        m_AM_Player_A_Look = m_AM_Player.FindAction("A_Look", throwIfNotFound: true);
        m_AM_Player_A_Sprint = m_AM_Player.FindAction("A_Sprint", throwIfNotFound: true);
        m_AM_Player_A_Jump = m_AM_Player.FindAction("A_Jump", throwIfNotFound: true);
    }

    ~@IA_Main()
    {
        UnityEngine.Debug.Assert(!m_AM_Player.enabled, "This will cause a leak and performance issues, IA_Main.AM_Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AM_Player
    private readonly InputActionMap m_AM_Player;
    private List<IAM_PlayerActions> m_AM_PlayerActionsCallbackInterfaces = new List<IAM_PlayerActions>();
    private readonly InputAction m_AM_Player_A_Move;
    private readonly InputAction m_AM_Player_A_Look;
    private readonly InputAction m_AM_Player_A_Sprint;
    private readonly InputAction m_AM_Player_A_Jump;
    /// <summary>
    /// Provides access to input actions defined in input action map "AM_Player".
    /// </summary>
    public struct AM_PlayerActions
    {
        private @IA_Main m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public AM_PlayerActions(@IA_Main wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "AM_Player/A_Move".
        /// </summary>
        public InputAction @A_Move => m_Wrapper.m_AM_Player_A_Move;
        /// <summary>
        /// Provides access to the underlying input action "AM_Player/A_Look".
        /// </summary>
        public InputAction @A_Look => m_Wrapper.m_AM_Player_A_Look;
        /// <summary>
        /// Provides access to the underlying input action "AM_Player/A_Sprint".
        /// </summary>
        public InputAction @A_Sprint => m_Wrapper.m_AM_Player_A_Sprint;
        /// <summary>
        /// Provides access to the underlying input action "AM_Player/A_Jump".
        /// </summary>
        public InputAction @A_Jump => m_Wrapper.m_AM_Player_A_Jump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_AM_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="AM_PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(AM_PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="AM_PlayerActions" />
        public void AddCallbacks(IAM_PlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_AM_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AM_PlayerActionsCallbackInterfaces.Add(instance);
            @A_Move.started += instance.OnA_Move;
            @A_Move.performed += instance.OnA_Move;
            @A_Move.canceled += instance.OnA_Move;
            @A_Look.started += instance.OnA_Look;
            @A_Look.performed += instance.OnA_Look;
            @A_Look.canceled += instance.OnA_Look;
            @A_Sprint.started += instance.OnA_Sprint;
            @A_Sprint.performed += instance.OnA_Sprint;
            @A_Sprint.canceled += instance.OnA_Sprint;
            @A_Jump.started += instance.OnA_Jump;
            @A_Jump.performed += instance.OnA_Jump;
            @A_Jump.canceled += instance.OnA_Jump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="AM_PlayerActions" />
        private void UnregisterCallbacks(IAM_PlayerActions instance)
        {
            @A_Move.started -= instance.OnA_Move;
            @A_Move.performed -= instance.OnA_Move;
            @A_Move.canceled -= instance.OnA_Move;
            @A_Look.started -= instance.OnA_Look;
            @A_Look.performed -= instance.OnA_Look;
            @A_Look.canceled -= instance.OnA_Look;
            @A_Sprint.started -= instance.OnA_Sprint;
            @A_Sprint.performed -= instance.OnA_Sprint;
            @A_Sprint.canceled -= instance.OnA_Sprint;
            @A_Jump.started -= instance.OnA_Jump;
            @A_Jump.performed -= instance.OnA_Jump;
            @A_Jump.canceled -= instance.OnA_Jump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="AM_PlayerActions.UnregisterCallbacks(IAM_PlayerActions)" />.
        /// </summary>
        /// <seealso cref="AM_PlayerActions.UnregisterCallbacks(IAM_PlayerActions)" />
        public void RemoveCallbacks(IAM_PlayerActions instance)
        {
            if (m_Wrapper.m_AM_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="AM_PlayerActions.AddCallbacks(IAM_PlayerActions)" />
        /// <seealso cref="AM_PlayerActions.RemoveCallbacks(IAM_PlayerActions)" />
        /// <seealso cref="AM_PlayerActions.UnregisterCallbacks(IAM_PlayerActions)" />
        public void SetCallbacks(IAM_PlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_AM_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AM_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="AM_PlayerActions" /> instance referencing this action map.
    /// </summary>
    public AM_PlayerActions @AM_Player => new AM_PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "AM_Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="AM_PlayerActions.AddCallbacks(IAM_PlayerActions)" />
    /// <seealso cref="AM_PlayerActions.RemoveCallbacks(IAM_PlayerActions)" />
    public interface IAM_PlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "A_Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA_Move(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "A_Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA_Look(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "A_Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA_Sprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "A_Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA_Jump(InputAction.CallbackContext context);
    }
}
